remove temporary changes

diff --git a/.github/workflows/spice-qa.yml b/.github/workflows/spice-qa.yml
--- a/.github/workflows/spice-qa.yml
+++ b/.github/workflows/spice-qa.yml
@@ -26,19 +26,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # - name: Create output directory
-      #   run: mkdir -p api_responses
+      - name: Create output directory
+        run: mkdir -p api_responses
 
-      # - name: Install Spice
-      #   shell: bash
-      #   run: |
-      #     curl https://install.spiceai.org | /bin/bash
-      #     echo "~/.spice/bin" >> $GITHUB_PATH
+      - name: Install Spice
+        shell: bash
+        run: |
+          curl https://install.spiceai.org | /bin/bash
+          echo "~/.spice/bin" >> $GITHUB_PATH
 
-      # - name: Verify Spice Installation
-      #   shell: bash
-      #   run: |
-      #     spice version
+      - name: Verify Spice Installation
+        shell: bash
+        run: |
+          spice version
 
       - name: Call Spice AI Completion API
         shell: bash
@@ -49,25 +49,25 @@ jobs:
           echo "RECIPE_FILE_PATH=$recipe_file_path" >> $GITHUB_ENV
           output_file="api_responses/${recipe_file_path}.log"
 
-      #     chat_input="Install Spice.ai OSS using the spiceai docs. Add it to the PATH. Verify installation of version '${{ github.event.inputs.spice_version }}' by running the CLI command spice version. Use the '${{ matrix.recipe_name }}' Recipe to conduct testing. Ensure you execute all instructions in the recipe. Ensure you report on the spice sql query or spice chat results if the recipe includes them."
+          chat_input="Install Spice.ai OSS using the spiceai docs. Add it to the PATH. Verify installation of version '${{ github.event.inputs.spice_version }}' by running the CLI command spice version. Use the '${{ matrix.recipe_name }}' Recipe to conduct testing. Ensure you execute all instructions in the recipe. Ensure you report on the spice sql query or spice chat results if the recipe includes them."
 
-      #     spice chat --cloud --http-endpoint https://data.spiceai.io --model timmy "$chat_input" > "$output_file" 2>&1
+          spice chat --cloud --http-endpoint https://data.spiceai.io --model timmy "$chat_input" > "$output_file" 2>&1
 
-      #     # Output response for debugging
-      #     echo "API Response saved to $output_file"
+          # Output response for debugging
+          echo "API Response saved to $output_file"
 
-      #     # Check for errors
-      #     if echo "$response" | grep -q "\"error\""; then
-      #       echo "Error detected in API response"
-      #       echo "$response"
-      #       exit 1
-      #     fi
+          # Check for errors
+          if echo "$response" | grep -q "\"error\""; then
+            echo "Error detected in API response"
+            echo "$response"
+            exit 1
+          fi
 
-      # - name: Upload response file
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: api-response-${{ env.RECIPE_FILE_PATH }}
-      #     path: api_responses/${{ env.RECIPE_FILE_PATH }}.log
+      - name: Upload response file
+        uses: actions/upload-artifact@v4
+        with:
+          name: api-response-${{ env.RECIPE_FILE_PATH }}
+          path: api_responses/${{ env.RECIPE_FILE_PATH }}.log
 
       - name: Check the spice-qa passing status
         shell: bash
