test e2e with streaming mode

diff --git a/.github/workflows/spice-qa.yml b/.github/workflows/spice-qa.yml
--- a/.github/workflows/spice-qa.yml
+++ b/.github/workflows/spice-qa.yml
@@ -34,65 +34,47 @@ jobs:
           recipe_file_path="$(echo "${{ matrix.recipe_name }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')"
           output_file="api_responses/${recipe_file_path}_stream.log"
 
-      #     curl -s \
-      #       -H "Content-Type: application/json" \
-      #       -H "X-API-Key: $SPICE_API_KEY" \
-      #       -d '{
-      #         "model": "timmy",
-      #         "messages": [
-      #           {
-      #             "role": "user",
-      #             "content": "Install Spice.ai OSS using the spiceai docs. Add it to the PATH. If it is already installed, run spice upgrade to upgrade it. Verify installation of version ${{ github.event.inputs.spice_version }} by running the CLI command spice version. Use the ${{ toJson(matrix.recipe_name) }} Recipe to conduct testing. Ensure you execute all instructions in the recipe. Ensure you report on the spice sql query or spice chat results if the recipe includes them."
-      #           }
-      #         ],
-      #         "temperature": 0.1
-      #       }' \
-      #       https://data.spiceai.io/v1/chat/completions
+          # Call API
+          response=$(curl -s \
+            -H "Content-Type: application/json" \
+            -H "X-API-Key: $SPICE_API_KEY" \
+            -d '{
+              "model": "timmy",
+              "messages": [
+                {
+                  "role": "user",
+                  "content": "Install Spice.ai OSS using the spiceai docs. Add it to the PATH. If it is already installed, run spice upgrade to upgrade it. Verify installation of version ${{ github.event.inputs.spice_version }} by running the CLI command spice version. Use the ${{ toJson(matrix.recipe_name) }} Recipe to conduct testing. Ensure you execute all instructions in the recipe. Ensure you report on the spice sql query or spice chat results if the recipe includes them."
+                }
+              ],
+              "temperature": 0.1,
+              "stream": true
+            }' \
+            https://data.spiceai.io/v1/chat/completions)
 
-      #     # Call API
-      #     response=$(curl -s \
-      #       -H "Content-Type: application/json" \
-      #       -H "X-API-Key: $SPICE_API_KEY" \
-      #       -d '{
-      #         "model": "timmy",
-      #         "messages": [
-      #           {
-      #             "role": "user",
-      #             "content": "Install Spice.ai OSS using the spiceai docs. Add it to the PATH. If it is already installed, run spice upgrade to upgrade it. Verify installation of version ${{ github.event.inputs.spice_version }} by running the CLI command spice version. Use the ${{ toJson(matrix.recipe_name) }} Recipe to conduct testing. Ensure you execute all instructions in the recipe. Ensure you report on the spice sql query or spice chat results if the recipe includes them."
-      #           }
-      #         ],
-      #         "temperature": 0.1
-      #       }' \
-      #       https://data.spiceai.io/v1/chat/completions)
+          # Save the response to a file
+          echo "$response" > $output_file
 
-      #     # Save the response to a file
-      #     echo "$response" > $output_file
+          # Output response for debugging
+          echo "Stream Chat Completion Response saved to $output_file"
 
-      #     # Output response for debugging
-      #     echo "Stream Chat Completion Response saved to $output_file"
-
-      #     # Check for errors
-      #     if echo "$response" | grep -q "\"error\""; then
-      #       echo "Error detected in API response"
-      #       echo "$response"
-      #       exit 1
-      #     fi
+          # Check for errors
+          if echo "$response" | grep -q "\"error\""; then
+            echo "Error detected in API response"
+            echo "$response"
+            exit 1
+          fi
 
       - name: Retrieve response from streaming result
         shell: bash
         env:
           SPICE_API_KEY: ${{ secrets.SPICE_API_KEY }}
         run: |
-          # input_file="api_responses/${recipe_file_path}_stream.log"
-          # output_file="api_responses/${recipe_file_path}.log"
-          input_file="api_responses/response_stream.log"
-          output_file="api_responses/response.log"
+          input_file="api_responses/${recipe_file_path}_stream.log"
+          output_file="api_responses/${recipe_file_path}.log"
           python .github/scripts/convert_stream.py "$input_file" "$output_file"
 
       - name: Upload response file
         uses: actions/upload-artifact@v4
         with:
-          # name: api-response-${recipe_file_path}
-          # path: api_responses/${recipe_file_path}.log
-          name: api-response-response
-          path: api_responses/response.log
+          name: api-response-${recipe_file_path}
+          path: api_responses/${recipe_file_path}.log
